GRANT INSERT,UPDATE ON DOCTOR TO receptionist; 
GRANT SELECT ON DOCTOR TO management; 
GRANT INSERT,UPDATE ON PATIENT TO receptionist; 
GRANT SELECT ON PATIENT TO PATIENT_LIST; 
GRANT INSERT,UPDATE ON DIAGNOSIS TO DOCTOR_LIST; 
GRANT SELECT ON DIAGNOSIS TO PATIENT_LIST; 
GRANT SELECT ON DEPARTMENT TO management; 
GRANT INSERT,UPDATE ON BILL TO receptionist; 
GRANT SELECT ON BILL TO PATIENT_LIST; 

