
CREATE VIEW VW_SNAPSHOT AS 
SELECT 
D.DOC_ID,
CONCAT(D.F_NAME,' ',D.L_NAME) AS DOCTOR,
P.PATIENT_ID,
CONCAT(P.F_NAME,' ',P.L_NAME) AS PATIENT,
DG.DIAG_DATE ,
DG.DIAG_TYPE , 
DG.SEVERITY ,
DG.TREATMENT ,
DG.PRESC_DRUGS ,
B.AMOUNT
FROM DOCTOR D
JOIN 
PATIENT P
ON D.DOC_ID = P.DOC_ID
JOIN DIAGNOSIS DG
ON P.PATIENT_ID = DG.PATIENT_ID
AND D.DOC_ID = DG.DOC_ID
JOIN BILL B
ON P.PATIENT_ID = B.PATIENT_ID AND
DG.DIAG_ID  = B.DIAG_ID 
ORDER BY DG.DIAG_DATE;


CREATE VIEW VW_DOC_PAT_RATIO_MAT AS 
SELECT 
CONCAT(D.F_NAME,' ',D.L_NAME) DOCTOR_NAME,
COUNT(P.PATIENT_ID)
FROM DOCTOR D
JOIN 
PATIENT P
ON D.DOC_ID = P.DOC_ID
JOIN DIAGNOSIS DG
ON P.PATIENT_ID = DG.PATIENT_ID
AND D.DOC_ID = DG.DOC_ID
GROUP BY D.DOC_ID
ORDER BY DG.DIAG_DATE;

CREATE VIEW VW_AILMENT_DIST_MAT AS 
SELECT 
P.GENDER ,
DG.DIAG_TYPE,
COUNT(P.PATIENT_ID) COUNT
FROM 
PATIENT P
JOIN DIAGNOSIS DG
ON P.PATIENT_ID = DG.PATIENT_ID
GROUP BY P.GENDER,DG.DIAG_TYPE
ORDER BY P.GENDER,DG.DIAG_TYPE;


