



CREATE PROCEDURE REVENUE_METRIX
AS
BEGIN
SELECT A.YEAR,
A.MONTH,
SUM(A.AMOUNT) AS REVENUE_MAT
FROM (SELECT 
EXTRACT(MONTH FROM BILL_DATE) AS MONTH,
EXTRACT(YEAR FROM BILL_DATE) AS YEAR,
AMOUNT
FROM BILL ) A
GROUP BY A.YEAR,A.MONTH
ORDER BY A.YEAR,A.MONTH
END;